tell application "Calendar"
	set bc_cal to calendar "BrandComposer"
	set rangeStart to date "Thursday, September 3, 2026 12:00:00 AM"
	set rangeEnd to date "Thursday, April 1, 2027 12:00:00 AM"
	delete (every event of bc_cal whose start date is greater than or equal to rangeStart and start date is less than rangeEnd)

	make new event at end of events of bc_cal with properties {summary:"[STORY] Karlie — Rotation baseline", start date:date "Thursday, September 3, 2026 1:00:00 PM", end date:date "Thursday, September 3, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Núria — Rotation baseline", start date:date "Friday, September 4, 2026 1:00:00 PM", end date:date "Friday, September 4, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Paula — Rotation baseline", start date:date "Monday, September 7, 2026 7:00:00 PM", end date:date "Monday, September 7, 2026 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Kate Bartlett — Rotation baseline", start date:date "Tuesday, September 8, 2026 1:00:00 PM", end date:date "Tuesday, September 8, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Erin — Rotation baseline", start date:date "Wednesday, September 9, 2026 1:00:00 PM", end date:date "Wednesday, September 9, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Amelie — Rotation baseline", start date:date "Thursday, September 10, 2026 7:00:00 PM", end date:date "Thursday, September 10, 2026 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Lily Collins — Rotation baseline", start date:date "Friday, September 11, 2026 1:00:00 PM", end date:date "Friday, September 11, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Renate — Rotation baseline", start date:date "Monday, September 14, 2026 1:00:00 PM", end date:date "Monday, September 14, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Rebecca — Rotation baseline", start date:date "Tuesday, September 15, 2026 7:00:00 PM", end date:date "Tuesday, September 15, 2026 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Gracie Abrams — Rotation baseline", start date:date "Wednesday, September 16, 2026 1:00:00 PM", end date:date "Wednesday, September 16, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Zendaya — Rotation baseline", start date:date "Thursday, September 17, 2026 1:00:00 PM", end date:date "Thursday, September 17, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Romy — Rotation baseline", start date:date "Friday, September 18, 2026 7:00:00 PM", end date:date "Friday, September 18, 2026 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Elle — Rotation baseline", start date:date "Monday, September 21, 2026 1:00:00 PM", end date:date "Monday, September 21, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Anya — Rotation baseline", start date:date "Tuesday, September 22, 2026 1:00:00 PM", end date:date "Tuesday, September 22, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Odessa — Rotation baseline", start date:date "Wednesday, September 23, 2026 7:00:00 PM", end date:date "Wednesday, September 23, 2026 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Olivia — Rotation baseline", start date:date "Thursday, September 24, 2026 1:00:00 PM", end date:date "Thursday, September 24, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Faith Ordway — Rotation baseline", start date:date "Friday, September 25, 2026 1:00:00 PM", end date:date "Friday, September 25, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Karlie — Rotation baseline", start date:date "Monday, September 28, 2026 7:00:00 PM", end date:date "Monday, September 28, 2026 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[POST] Odessa — Debut carousel, Stranger Things S2 momentum", start date:date "Tuesday, September 29, 2026 9:00:00 AM", end date:date "Tuesday, September 29, 2026 9:15:00 AM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Odessa — Slide 1", start date:date "Tuesday, September 29, 2026 1:00:00 PM", end date:date "Tuesday, September 29, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Odessa — Slide 2", start date:date "Tuesday, September 29, 2026 7:00:00 PM", end date:date "Tuesday, September 29, 2026 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Núria — Rotation baseline", start date:date "Wednesday, September 30, 2026 1:00:00 PM", end date:date "Wednesday, September 30, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[POST] Syd — Debut carousel, rotation placement (no dated hook)", start date:date "Thursday, October 1, 2026 9:00:00 AM", end date:date "Thursday, October 1, 2026 9:15:00 AM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Syd — Slide 1", start date:date "Thursday, October 1, 2026 1:00:00 PM", end date:date "Thursday, October 1, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Syd — Slide 2", start date:date "Thursday, October 1, 2026 7:00:00 PM", end date:date "Thursday, October 1, 2026 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Paula — Rotation baseline", start date:date "Friday, October 2, 2026 1:00:00 PM", end date:date "Friday, October 2, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Kate Bartlett — Rotation baseline", start date:date "Monday, October 5, 2026 7:00:00 PM", end date:date "Monday, October 5, 2026 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Erin — Rotation baseline", start date:date "Tuesday, October 6, 2026 1:00:00 PM", end date:date "Tuesday, October 6, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Amelie — Rotation baseline", start date:date "Wednesday, October 7, 2026 1:00:00 PM", end date:date "Wednesday, October 7, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[POST] Katrin — Debut carousel, rotation placement (no dated hook)", start date:date "Thursday, October 8, 2026 9:00:00 AM", end date:date "Thursday, October 8, 2026 9:15:00 AM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Katrin — Slide 1", start date:date "Thursday, October 8, 2026 1:00:00 PM", end date:date "Thursday, October 8, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Katrin — Slide 2", start date:date "Thursday, October 8, 2026 7:00:00 PM", end date:date "Thursday, October 8, 2026 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Lily Collins — Rotation baseline", start date:date "Friday, October 9, 2026 7:00:00 PM", end date:date "Friday, October 9, 2026 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Romy — 30th birthday HOOK", start date:date "Sunday, October 11, 2026 1:00:00 PM", end date:date "Sunday, October 11, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Renate — Rotation baseline", start date:date "Monday, October 12, 2026 1:00:00 PM", end date:date "Monday, October 12, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Rebecca — Rotation baseline", start date:date "Tuesday, October 13, 2026 1:00:00 PM", end date:date "Tuesday, October 13, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Gracie Abrams — Rotation baseline", start date:date "Wednesday, October 14, 2026 7:00:00 PM", end date:date "Wednesday, October 14, 2026 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[POST] Emma — Debut, single image, rotation placement (no dated hook)", start date:date "Thursday, October 15, 2026 9:00:00 AM", end date:date "Thursday, October 15, 2026 9:15:00 AM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Emma — The image", start date:date "Thursday, October 15, 2026 1:00:00 PM", end date:date "Thursday, October 15, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Zendaya — Rotation baseline", start date:date "Friday, October 16, 2026 1:00:00 PM", end date:date "Friday, October 16, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Rebecca — 43rd birthday HOOK", start date:date "Monday, October 19, 2026 1:00:00 PM", end date:date "Monday, October 19, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Romy — Rotation baseline", start date:date "Tuesday, October 20, 2026 1:00:00 PM", end date:date "Tuesday, October 20, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Elle — Rotation baseline", start date:date "Wednesday, October 21, 2026 7:00:00 PM", end date:date "Wednesday, October 21, 2026 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Anya — Rotation baseline", start date:date "Thursday, October 22, 2026 1:00:00 PM", end date:date "Thursday, October 22, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Odessa — Rotation baseline", start date:date "Friday, October 23, 2026 1:00:00 PM", end date:date "Friday, October 23, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Olivia — Rotation baseline", start date:date "Monday, October 26, 2026 7:00:00 PM", end date:date "Monday, October 26, 2026 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Faith Ordway — Rotation baseline", start date:date "Tuesday, October 27, 2026 1:00:00 PM", end date:date "Tuesday, October 27, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Syd — Rotation baseline", start date:date "Wednesday, October 28, 2026 1:00:00 PM", end date:date "Wednesday, October 28, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Katrin — Rotation baseline", start date:date "Thursday, October 29, 2026 7:00:00 PM", end date:date "Thursday, October 29, 2026 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Emma — Rotation baseline", start date:date "Friday, October 30, 2026 1:00:00 PM", end date:date "Friday, October 30, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Karlie — Rotation baseline", start date:date "Monday, November 2, 2026 1:00:00 PM", end date:date "Monday, November 2, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Núria — Rotation baseline", start date:date "Tuesday, November 3, 2026 7:00:00 PM", end date:date "Tuesday, November 3, 2026 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Paula — Rotation baseline", start date:date "Wednesday, November 4, 2026 1:00:00 PM", end date:date "Wednesday, November 4, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Kate Bartlett — Rotation baseline", start date:date "Thursday, November 5, 2026 1:00:00 PM", end date:date "Thursday, November 5, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Erin — Rotation baseline", start date:date "Friday, November 6, 2026 7:00:00 PM", end date:date "Friday, November 6, 2026 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Amelie — Rotation baseline", start date:date "Monday, November 9, 2026 1:00:00 PM", end date:date "Monday, November 9, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Lily Collins — Rotation baseline", start date:date "Tuesday, November 10, 2026 1:00:00 PM", end date:date "Tuesday, November 10, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Renate — Rotation baseline", start date:date "Wednesday, November 11, 2026 7:00:00 PM", end date:date "Wednesday, November 11, 2026 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Rebecca — Rotation baseline", start date:date "Thursday, November 12, 2026 1:00:00 PM", end date:date "Thursday, November 12, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Gracie Abrams — Rotation baseline", start date:date "Friday, November 13, 2026 1:00:00 PM", end date:date "Friday, November 13, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Zendaya — Rotation baseline", start date:date "Monday, November 16, 2026 7:00:00 PM", end date:date "Monday, November 16, 2026 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Romy — Rotation baseline", start date:date "Tuesday, November 17, 2026 1:00:00 PM", end date:date "Tuesday, November 17, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Elle — Rotation baseline", start date:date "Wednesday, November 18, 2026 1:00:00 PM", end date:date "Wednesday, November 18, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[POST] Elle — Elle II debut carousel, Hunger Games eve", start date:date "Thursday, November 19, 2026 9:00:00 AM", end date:date "Thursday, November 19, 2026 9:15:00 AM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Elle — Slide 1", start date:date "Thursday, November 19, 2026 1:00:00 PM", end date:date "Thursday, November 19, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Elle — Slide 2", start date:date "Thursday, November 19, 2026 7:00:00 PM", end date:date "Thursday, November 19, 2026 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Elle — Hunger Games: Sunrise on the Reaping HOOK", start date:date "Friday, November 20, 2026 1:00:00 PM", end date:date "Friday, November 20, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Anya — Rotation baseline", start date:date "Monday, November 23, 2026 7:00:00 PM", end date:date "Monday, November 23, 2026 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Odessa — Rotation baseline", start date:date "Tuesday, November 24, 2026 1:00:00 PM", end date:date "Tuesday, November 24, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Olivia — Rotation baseline", start date:date "Wednesday, November 25, 2026 1:00:00 PM", end date:date "Wednesday, November 25, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Faith Ordway — Rotation baseline", start date:date "Thursday, November 26, 2026 7:00:00 PM", end date:date "Thursday, November 26, 2026 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Syd — Rotation baseline", start date:date "Friday, November 27, 2026 1:00:00 PM", end date:date "Friday, November 27, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Katrin — Rotation baseline", start date:date "Monday, November 30, 2026 1:00:00 PM", end date:date "Monday, November 30, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Emma — Rotation baseline", start date:date "Tuesday, December 1, 2026 7:00:00 PM", end date:date "Tuesday, December 1, 2026 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Gracie Abrams — Tour launch HOOK", start date:date "Wednesday, December 2, 2026 1:00:00 PM", end date:date "Wednesday, December 2, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Karlie — Rotation baseline", start date:date "Thursday, December 3, 2026 1:00:00 PM", end date:date "Thursday, December 3, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Núria — Rotation baseline", start date:date "Friday, December 4, 2026 1:00:00 PM", end date:date "Friday, December 4, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Paula — Rotation baseline", start date:date "Monday, December 7, 2026 7:00:00 PM", end date:date "Monday, December 7, 2026 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Kate Bartlett — Rotation baseline", start date:date "Tuesday, December 8, 2026 1:00:00 PM", end date:date "Tuesday, December 8, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Erin — Rotation baseline", start date:date "Wednesday, December 9, 2026 1:00:00 PM", end date:date "Wednesday, December 9, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Amelie — Rotation baseline", start date:date "Thursday, December 10, 2026 7:00:00 PM", end date:date "Thursday, December 10, 2026 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Lily Collins — Rotation baseline", start date:date "Friday, December 11, 2026 1:00:00 PM", end date:date "Friday, December 11, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Renate — Rotation baseline", start date:date "Monday, December 14, 2026 1:00:00 PM", end date:date "Monday, December 14, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Rebecca — Rotation baseline", start date:date "Tuesday, December 15, 2026 7:00:00 PM", end date:date "Tuesday, December 15, 2026 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Gracie Abrams — Rotation baseline", start date:date "Wednesday, December 16, 2026 1:00:00 PM", end date:date "Wednesday, December 16, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Zendaya — Rotation baseline", start date:date "Thursday, December 17, 2026 1:00:00 PM", end date:date "Thursday, December 17, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Zendaya — Dune: Part Three HOOK", start date:date "Friday, December 18, 2026 9:00:00 AM", end date:date "Friday, December 18, 2026 9:15:00 AM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Anya — Dune: Part Three HOOK", start date:date "Friday, December 18, 2026 1:00:00 PM", end date:date "Friday, December 18, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Rebecca — Dune: Part Three HOOK", start date:date "Friday, December 18, 2026 7:00:00 PM", end date:date "Friday, December 18, 2026 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Romy — Rotation baseline", start date:date "Monday, December 21, 2026 7:00:00 PM", end date:date "Monday, December 21, 2026 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Elle — Rotation baseline", start date:date "Tuesday, December 22, 2026 1:00:00 PM", end date:date "Tuesday, December 22, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Anya — Rotation baseline", start date:date "Wednesday, December 23, 2026 1:00:00 PM", end date:date "Wednesday, December 23, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Odessa — Rotation baseline", start date:date "Thursday, December 24, 2026 7:00:00 PM", end date:date "Thursday, December 24, 2026 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Olivia — Rotation baseline", start date:date "Friday, December 25, 2026 1:00:00 PM", end date:date "Friday, December 25, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Faith Ordway — Rotation baseline", start date:date "Monday, December 28, 2026 1:00:00 PM", end date:date "Monday, December 28, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Syd — Rotation baseline", start date:date "Tuesday, December 29, 2026 7:00:00 PM", end date:date "Tuesday, December 29, 2026 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Katrin — Rotation baseline", start date:date "Wednesday, December 30, 2026 1:00:00 PM", end date:date "Wednesday, December 30, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Emma — Rotation baseline", start date:date "Thursday, December 31, 2026 1:00:00 PM", end date:date "Thursday, December 31, 2026 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Karlie — Rotation baseline", start date:date "Friday, January 1, 2027 7:00:00 PM", end date:date "Friday, January 1, 2027 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Núria — Rotation baseline", start date:date "Monday, January 4, 2027 1:00:00 PM", end date:date "Monday, January 4, 2027 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Paula — Rotation baseline", start date:date "Tuesday, January 5, 2027 1:00:00 PM", end date:date "Tuesday, January 5, 2027 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Kate Bartlett — Rotation baseline", start date:date "Wednesday, January 6, 2027 7:00:00 PM", end date:date "Wednesday, January 6, 2027 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Erin — Rotation baseline", start date:date "Thursday, January 7, 2027 1:00:00 PM", end date:date "Thursday, January 7, 2027 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Amelie — Rotation baseline", start date:date "Friday, January 8, 2027 1:00:00 PM", end date:date "Friday, January 8, 2027 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Lily Collins — Rotation baseline", start date:date "Monday, January 11, 2027 7:00:00 PM", end date:date "Monday, January 11, 2027 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Renate — Rotation baseline", start date:date "Tuesday, January 12, 2027 1:00:00 PM", end date:date "Tuesday, January 12, 2027 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Rebecca — Rotation baseline", start date:date "Wednesday, January 13, 2027 1:00:00 PM", end date:date "Wednesday, January 13, 2027 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Gracie Abrams — Rotation baseline", start date:date "Thursday, January 14, 2027 7:00:00 PM", end date:date "Thursday, January 14, 2027 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Zendaya — Rotation baseline", start date:date "Friday, January 15, 2027 1:00:00 PM", end date:date "Friday, January 15, 2027 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Romy — Rotation baseline", start date:date "Monday, January 18, 2027 1:00:00 PM", end date:date "Monday, January 18, 2027 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Elle — Rotation baseline", start date:date "Tuesday, January 19, 2027 7:00:00 PM", end date:date "Tuesday, January 19, 2027 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Anya — Rotation baseline", start date:date "Wednesday, January 20, 2027 1:00:00 PM", end date:date "Wednesday, January 20, 2027 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Odessa — Rotation baseline", start date:date "Thursday, January 21, 2027 1:00:00 PM", end date:date "Thursday, January 21, 2027 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Olivia — Rotation baseline", start date:date "Friday, January 22, 2027 7:00:00 PM", end date:date "Friday, January 22, 2027 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Faith Ordway — Rotation baseline", start date:date "Monday, January 25, 2027 1:00:00 PM", end date:date "Monday, January 25, 2027 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Syd — Rotation baseline", start date:date "Tuesday, January 26, 2027 1:00:00 PM", end date:date "Tuesday, January 26, 2027 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Katrin — Rotation baseline", start date:date "Wednesday, January 27, 2027 7:00:00 PM", end date:date "Wednesday, January 27, 2027 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Emma — Rotation baseline", start date:date "Thursday, January 28, 2027 1:00:00 PM", end date:date "Thursday, January 28, 2027 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Karlie — Rotation baseline", start date:date "Friday, January 29, 2027 1:00:00 PM", end date:date "Friday, January 29, 2027 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Núria — Rotation baseline", start date:date "Monday, February 1, 2027 7:00:00 PM", end date:date "Monday, February 1, 2027 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Paula — Rotation baseline", start date:date "Tuesday, February 2, 2027 1:00:00 PM", end date:date "Tuesday, February 2, 2027 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Kate Bartlett — Rotation baseline", start date:date "Wednesday, February 3, 2027 1:00:00 PM", end date:date "Wednesday, February 3, 2027 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Erin — Rotation baseline", start date:date "Thursday, February 4, 2027 7:00:00 PM", end date:date "Thursday, February 4, 2027 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Amelie — Rotation baseline", start date:date "Friday, February 5, 2027 1:00:00 PM", end date:date "Friday, February 5, 2027 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Lily Collins — Rotation baseline", start date:date "Monday, February 8, 2027 1:00:00 PM", end date:date "Monday, February 8, 2027 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Renate — Rotation baseline", start date:date "Tuesday, February 9, 2027 7:00:00 PM", end date:date "Tuesday, February 9, 2027 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Rebecca — Rotation baseline", start date:date "Wednesday, February 10, 2027 1:00:00 PM", end date:date "Wednesday, February 10, 2027 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Gracie Abrams — Rotation baseline", start date:date "Thursday, February 11, 2027 1:00:00 PM", end date:date "Thursday, February 11, 2027 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Zendaya — Rotation baseline", start date:date "Friday, February 12, 2027 7:00:00 PM", end date:date "Friday, February 12, 2027 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Romy — Rotation baseline", start date:date "Monday, February 15, 2027 1:00:00 PM", end date:date "Monday, February 15, 2027 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Elle — Rotation baseline", start date:date "Tuesday, February 16, 2027 1:00:00 PM", end date:date "Tuesday, February 16, 2027 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Anya — Rotation baseline", start date:date "Wednesday, February 17, 2027 7:00:00 PM", end date:date "Wednesday, February 17, 2027 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Odessa — Rotation baseline", start date:date "Thursday, February 18, 2027 1:00:00 PM", end date:date "Thursday, February 18, 2027 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Olivia — Rotation baseline", start date:date "Friday, February 19, 2027 1:00:00 PM", end date:date "Friday, February 19, 2027 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Faith Ordway — Rotation baseline", start date:date "Monday, February 22, 2027 7:00:00 PM", end date:date "Monday, February 22, 2027 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Syd — Rotation baseline", start date:date "Tuesday, February 23, 2027 1:00:00 PM", end date:date "Tuesday, February 23, 2027 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Katrin — Rotation baseline", start date:date "Wednesday, February 24, 2027 1:00:00 PM", end date:date "Wednesday, February 24, 2027 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Emma — Rotation baseline", start date:date "Thursday, February 25, 2027 7:00:00 PM", end date:date "Thursday, February 25, 2027 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Karlie — Rotation baseline", start date:date "Friday, February 26, 2027 1:00:00 PM", end date:date "Friday, February 26, 2027 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Núria — Rotation baseline", start date:date "Monday, March 1, 2027 1:00:00 PM", end date:date "Monday, March 1, 2027 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Paula — Rotation baseline", start date:date "Tuesday, March 2, 2027 7:00:00 PM", end date:date "Tuesday, March 2, 2027 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Kate Bartlett — Rotation baseline", start date:date "Wednesday, March 3, 2027 1:00:00 PM", end date:date "Wednesday, March 3, 2027 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Erin — Rotation baseline", start date:date "Thursday, March 4, 2027 1:00:00 PM", end date:date "Thursday, March 4, 2027 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Amelie — Rotation baseline", start date:date "Friday, March 5, 2027 7:00:00 PM", end date:date "Friday, March 5, 2027 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Lily Collins — Rotation baseline", start date:date "Monday, March 8, 2027 1:00:00 PM", end date:date "Monday, March 8, 2027 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Renate — Rotation baseline", start date:date "Tuesday, March 9, 2027 1:00:00 PM", end date:date "Tuesday, March 9, 2027 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Rebecca — Rotation baseline", start date:date "Wednesday, March 10, 2027 7:00:00 PM", end date:date "Wednesday, March 10, 2027 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Gracie Abrams — Rotation baseline", start date:date "Thursday, March 11, 2027 1:00:00 PM", end date:date "Thursday, March 11, 2027 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Zendaya — Rotation baseline", start date:date "Friday, March 12, 2027 1:00:00 PM", end date:date "Friday, March 12, 2027 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Romy — Rotation baseline", start date:date "Monday, March 15, 2027 7:00:00 PM", end date:date "Monday, March 15, 2027 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Elle — Rotation baseline", start date:date "Tuesday, March 16, 2027 1:00:00 PM", end date:date "Tuesday, March 16, 2027 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Anya — Rotation baseline", start date:date "Wednesday, March 17, 2027 1:00:00 PM", end date:date "Wednesday, March 17, 2027 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Lily Collins — 38th birthday + Emily in Paris HOOK", start date:date "Thursday, March 18, 2027 1:00:00 PM", end date:date "Thursday, March 18, 2027 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Elle — The Nightingale HOOK", start date:date "Friday, March 19, 2027 1:00:00 PM", end date:date "Friday, March 19, 2027 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Odessa — Rotation baseline", start date:date "Monday, March 22, 2027 7:00:00 PM", end date:date "Monday, March 22, 2027 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Olivia — Rotation baseline", start date:date "Tuesday, March 23, 2027 1:00:00 PM", end date:date "Tuesday, March 23, 2027 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Faith Ordway — Rotation baseline", start date:date "Wednesday, March 24, 2027 1:00:00 PM", end date:date "Wednesday, March 24, 2027 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Syd — Rotation baseline", start date:date "Thursday, March 25, 2027 7:00:00 PM", end date:date "Thursday, March 25, 2027 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Katrin — Rotation baseline", start date:date "Friday, March 26, 2027 1:00:00 PM", end date:date "Friday, March 26, 2027 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Emma — Rotation baseline", start date:date "Monday, March 29, 2027 1:00:00 PM", end date:date "Monday, March 29, 2027 1:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Karlie — Rotation baseline", start date:date "Tuesday, March 30, 2027 7:00:00 PM", end date:date "Tuesday, March 30, 2027 7:15:00 PM"}
	make new event at end of events of bc_cal with properties {summary:"[STORY] Núria — Rotation baseline", start date:date "Wednesday, March 31, 2027 1:00:00 PM", end date:date "Wednesday, March 31, 2027 1:15:00 PM"}

end tell

display notification "BrandComposer calendar rebuilt with 162 events." with title "Calendar Update Complete"
